# Generated by Django 5.2.13 on 2026-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mine_chat", "0002_chatsession_owner"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="role",
            field=models.CharField(choices=[("user", "사용자"), ("assistant", "AI")], max_length=20),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="title",
            field=models.CharField(default="새 채팅", max_length=120),
        ),
    ]
