# Generated by Django 5.2.14 on 2026-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mine_chat', '0003_alter_chatmessage_role_alter_chatsession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
