# Generated by Codex on 2026-06-22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("community", "0002_post_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="image",
        ),
    ]
